const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],KEY='apple-resume-jjb-v9';let timer;
const toast=$('#toast');function say(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)}
function save(){localStorage.setItem(KEY,$('#resume').innerHTML);say('已自动保存')}function bind(){ $$('.delete').forEach(b=>b.onclick=()=>{b.closest('.editable-item').remove();save()}) }
function reveal(){const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});$$('.reveal').forEach(x=>o.observe(x))}
const saved=localStorage.getItem(KEY);if(saved)$('#resume').innerHTML=saved;$('#year').textContent=new Date().getFullYear();bind();reveal();
$('#resume').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(save,600)});
$('#editButton').onclick=()=>{$('#editor').classList.toggle('open');document.body.classList.toggle('editing',$('#editor').classList.contains('open'))};$('#closeEditor').onclick=()=>{$('#editor').classList.remove('open');document.body.classList.remove('editing')};
$('#themeBtn').onclick=()=>{const dark=document.documentElement.dataset.dark!=='true';document.documentElement.dataset.dark=dark;localStorage.setItem('apple-theme',dark)};document.documentElement.dataset.dark=localStorage.getItem('apple-theme')||'false';
$('#addJob').onclick=()=>{const a=document.createElement('article');a.className='job editable-item reveal visible';a.innerHTML='<div><time contenteditable="true">20XX — 20XX</time><h3 contenteditable="true">职位名称</h3><p contenteditable="true">公司名称 · 城市</p></div><div><p contenteditable="true">写下职责、关键行动和量化成果。</p><ul><li contenteditable="true">核心能力或成果</li><li contenteditable="true">核心能力或成果</li></ul></div><button class="delete">×</button>';$('#jobList').append(a);bind();save();a.scrollIntoView({behavior:'smooth',block:'center'})};
$('#addWork').onclick=()=>{const a=document.createElement('article');a.className='work-card editable-item reveal visible';a.innerHTML='<div class="work-copy"><span contenteditable="true">PROJECT · 20XX</span><h3 contenteditable="true">项目名称</h3><p contenteditable="true">说明项目价值、你的角色和最终成果。</p><a contenteditable="true" href="#">查看案例 <b>›</b></a></div><div class="visual violet"><div class="sphere"></div></div><button class="delete">×</button>';$('#workGrid').append(a);bind();save();a.scrollIntoView({behavior:'smooth',block:'center'})};
$('#exportBtn').onclick=()=>{const b=new Blob([JSON.stringify({html:$('#resume').innerHTML,dark:document.documentElement.dataset.dark},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='Apple风格简历内容.json';a.click();URL.revokeObjectURL(a.href)};$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);$('#resume').innerHTML=d.html;document.documentElement.dataset.dark=d.dark||'false';bind();save();location.reload()}catch{say('文件格式错误')}};r.readAsText(e.target.files[0])};$('#printBtn').onclick=()=>print();$('#resetBtn').onclick=()=>{if(confirm('确定恢复示例内容？')){localStorage.removeItem(KEY);location.reload()}};
